### ISSUE TITLE
Update images for SteemMakers Trail page 

### ISSUE THREAD

**Issue by frankremmy** [JefPatat/SteemMakers#32]
#### Image 1
![steemconnect](https://user-images.githubusercontent.com/37175426/43464178-49c37d88-94d2-11e8-87e9-a28ed48c81f0.JPG)
#### Image 2
![steemconnect2](https://user-images.githubusercontent.com/37175426/43466375-4e266b92-94d7-11e8-8982-f86ad9b7797b.JPG)
#### Image 3
![authorize steemauto](https://user-images.githubusercontent.com/37175426/43466405-5cdba814-94d7-11e8-958f-ec0ff7da9e04.png)
#### Image 4
![steemmakerstrail7](https://user-images.githubusercontent.com/37175426/43466441-70e2860c-94d7-11e8-9fdb-5e8388706d4b.png)
#### Image 5
![steemauto dashboard](https://user-images.githubusercontent.com/37175426/43466594-ca9431e6-94d7-11e8-88e7-b6b2fd6581f3.png)
#### Image 6
![search for steemmakers](https://user-images.githubusercontent.com/37175426/43466635-e08ab95c-94d7-11e8-925a-286966004277.png)
#### Image 7
![follow our trail](https://user-images.githubusercontent.com/37175426/43466723-137d5ba8-94d8-11e8-85a8-bb4857aff6e3.png)
#### Image 8
![steemmakers trail followed](https://user-images.githubusercontent.com/37175426/43467124-f06fb47a-94d8-11e8-88ab-17343b037de2.png)
#### Image 9 
![steemmakerstrail10](https://user-images.githubusercontent.com/37175426/43467322-6241603a-94d9-11e8-9924-55a21961159d.png)

**Comment by frankremmy** [comment]
Image for the merged PR #28

**Comment by frankremmy** [comment]
The texts and the images are well arranged and presented in this document 
https://1drv.ms/w/s!AmsMPZ07DfJ-gRiAydkFKG3V2T98 for better reference when used on the site.

**Comment by JefPatat** [comment]
Thank you Frankremmy
