### ISSUE TITLE
Cross Site Scripting (XSS) Vulnerability Found On SteemMakers 

### ISSUE THREAD

**Issue by emirfirlar** [JefPatat/SteemMakers#9]
I checked Cross site scripting (CSS-XSS) vulnerability on SteemMakers. One of these experiments reflected a cookie on the screen. It is not good that such important vulnerability was present on SteemMakers.

   Cross site scripting (CSS-XSS) is a high priority vulnerability that allows an attacker to send malicious code (usually in the form of Javascript) to another user. XSS – CSS , takes part at OWASP PHP security vulnerability TOP 5 list. SteemMakers is vulnerable to Cross Site Scripting injection vulnerability. Malicious users may gather data with use this vulnerability. Malicious users may inject JavaScript, VBScript, ActiveX, HTML or Flash into a vulnerable application to gather data from them.

You can reflect the XSS cookie to the screen using the following code:

`https://www.steemmakers.com/?limit='"()<ScRiPt >alert('!!! XSS Vulnerability Found by emirfirlar !!!')</ScRiPt>`

* You can see the XSS Cookie Gif's below:

&emsp;

<center>https://media.giphy.com/media/5pWN2lDE8pL2191rOS/giphy.gif</center>

&emsp;

* You can see the XSS Cookie in the video in detail below:

&emsp;

<iframe width="1263" height="519" src="https://www.youtube.com/embed/oEL2UdIzihU" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

* You can see the Xss detail in source below

&emsp;

<center>![Ekran Alıntısı.JPG](https://steemitimages.com/DQmTGMka2TtKj3WqBMKcyM7d1eGCv2q1PCxYReDkXkxbGGz/Ekran%20Al%C4%B1nt%C4%B1s%C4%B1.JPG)</center>

**Comment by JefPatat** [comment]
Issue has been solved in redesigned website
